version: "3.9"

services:
  server:
    build: ./server
    ports:
      - "8000:3000"
    volumes:
      - ./server:/server
    depends_on: 
      - db 
    restart: always
    
  db:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: user
      POSTGRES_DB: todoList
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
